version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "chore: "
      include: "scope"
    auto-merge:
      enabled: true
      method: "merge"
      min-approval-reviews: 0
    reviewers:
      - "janie314"
    allow:
      - dependency-type: "all"
