name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: cargo build
        run: cargo build --verbose

      - name: Run subshift help
        run: cargo run -- -h

      - name: cargo test
        run: cargo test --verbose

      - name: Check formatting
        run: cargo fmt -- --check

      - name: cargo check
        run: cargo check --verbose
